INSERT INTO questions (text, answer, category, time_limit) VALUES
-- HISTORY (60 questions)
('In what year did World War II end?', 1945, 'history', 15),
('In what year did World War I begin?', 1914, 'history', 15),
('In what year did the Berlin Wall fall?', 1989, 'history', 15),
('In what year did Neil Armstrong walk on the Moon?', 1969, 'history', 15),
('In what year was the United States Declaration of Independence signed?', 1776, 'history', 15),
('In what year did the Titanic sink?', 1912, 'history', 15),
('In what year did the French Revolution begin?', 1789, 'history', 15),
('In what year was the Magna Carta signed?', 1215, 'history', 15),
('In what year did Columbus first reach the Americas?', 1492, 'history', 15),
('In what year was the Soviet Union dissolved?', 1991, 'history', 15),
('In what year did the first iPhone launch?', 2007, 'history', 15),
('In what year was Nelson Mandela released from prison?', 1990, 'history', 15),
('In what year did the Cold War end?', 1991, 'history', 15),
('In what year was the Roman Empire founded?', 27, 'history', 15),
('In what year did the Black Death peak in Europe?', 1347, 'history', 15),
('In what year did Adolf Hitler come to power in Germany?', 1933, 'history', 15),
('In what year was the United Nations founded?', 1945, 'history', 15),
('In what year did the Korean War end?', 1953, 'history', 15),
('In what year was the printing press invented by Gutenberg?', 1440, 'history', 15),
('In what year did the Vietnam War end?', 1975, 'history', 15),
('In what year was Barack Obama first elected US President?', 2008, 'history', 15),
('In what year did the Great Fire of London occur?', 1666, 'history', 15),
('How many years did Nelson Mandela spend in prison?', 27, 'history', 15),
('In what year was the Eiffel Tower completed?', 1889, 'history', 15),
('In what year did the Chernobyl disaster occur?', 1986, 'history', 15),
('In what year was the Colosseum in Rome completed?', 80, 'history', 15),
('In what year did the Gulf War begin?', 1990, 'history', 15),
('In what year was the first Olympic Games of the modern era held?', 1896, 'history', 15),
('In what year did the Space Shuttle Columbia disaster occur?', 2003, 'history', 15),
('In what year was NATO founded?', 1949, 'history', 15),
('In what year did the Cuban Missile Crisis occur?', 1962, 'history', 15),
('In what year was the Suez Canal opened?', 1869, 'history', 15),
('In what year was the first atomic bomb dropped on Hiroshima?', 1945, 'history', 15),
('In what year was the Bastille stormed?', 1789, 'history', 15),
('In what year did India gain independence from Britain?', 1947, 'history', 15),
('How many US Presidents have been assassinated?', 4, 'history', 15),
('In what year was the Panama Canal completed?', 1914, 'history', 15),
('In what year did the September 11 attacks occur?', 2001, 'history', 15),
('In what year was the first email sent?', 1971, 'history', 15),
('In what year was the Euro introduced as a physical currency?', 2002, 'history', 15),
('In what year was the Great Wall of China construction begun?', 221, 'history', 15),
('In what year was Mahatma Gandhi assassinated?', 1948, 'history', 15),
('How many days did the Hundred Years War last in total years?', 116, 'history', 15),
('In what year was the first World Cup held?', 1930, 'history', 15),
('In what year was the Hiroshima atomic bomb dropped?', 1945, 'history', 15),
('In what year was the Rosetta Stone discovered?', 1799, 'history', 15),
('In what year did the Rwandan genocide occur?', 1994, 'history', 15),
('In what year was the internet made publicly available?', 1991, 'history', 15),
('In what year was Abraham Lincoln assassinated?', 1865, 'history', 15),
('In what year did Napoleon Bonaparte die?', 1821, 'history', 15),
('How many amendments does the US Constitution have?', 27, 'history', 15),
('In what year was the first iPhone released?', 2007, 'history', 15),
('In what year was Adolf Hitler born?', 1889, 'history', 15),
('In what year did the Space Shuttle Challenger explode?', 1986, 'history', 15),
('In what year was the State of Israel founded?', 1948, 'history', 15),
('In what year was the Statue of Liberty unveiled?', 1886, 'history', 15),
('In what year did the First Crusade begin?', 1096, 'history', 15),
('In what year was the telephone invented by Alexander Graham Bell?', 1876, 'history', 15),
('How many years did the Thirty Years War last?', 30, 'history', 15),
('In what year was the Treaty of Versailles signed?', 1919, 'history', 15),

-- SCIENCE (60 questions)
('How many bones are in the adult human body?', 206, 'science', 15),
('What is the atomic number of gold?', 79, 'science', 15),
('How many chromosomes do humans have?', 46, 'science', 15),
('What is the speed of light in km/s (rounded)?', 300000, 'science', 15),
('How many elements are on the periodic table?', 118, 'science', 15),
('What is the boiling point of water in Celsius?', 100, 'science', 15),
('How many teeth does an adult human have (including wisdom teeth)?', 32, 'science', 15),
('What is the freezing point of water in Fahrenheit?', 32, 'science', 15),
('How many moons does Mars have?', 2, 'science', 15),
('How many hearts does an octopus have?', 3, 'science', 15),
('In what year was penicillin discovered?', 1928, 'science', 15),
('How many pairs of ribs does a human have?', 12, 'science', 15),
('What is the atomic number of carbon?', 6, 'science', 15),
('How many seconds are in one hour?', 3600, 'science', 15),
('How many days does it take Earth to orbit the Sun?', 365, 'science', 15),
('How many planets are in our solar system?', 8, 'science', 15),
('What is the normal human body temperature in Celsius?', 37, 'science', 15),
('How many moons does Jupiter have?', 95, 'science', 15),
('What is the atomic number of oxygen?', 8, 'science', 15),
('How many muscles are in the human body (approximately)?', 600, 'science', 15),
('How many chambers does the human heart have?', 4, 'science', 15),
('What is the melting point of iron in Celsius (approximately)?', 1538, 'science', 15),
('How many light-years away is the nearest star (Proxima Centauri, rounded)?', 4, 'science', 15),
('How many bones are in the human hand?', 27, 'science', 15),
('In what year did Albert Einstein publish the theory of general relativity?', 1915, 'science', 15),
('How many vertebrae does the human spine have?', 33, 'science', 15),
('What is the diameter of Earth in kilometers (rounded to nearest thousand)?', 13000, 'science', 15),
('How many liters of blood does the average adult have?', 5, 'science', 15),
('How many eyes does a spider have?', 8, 'science', 15),
('What is the atomic number of iron?', 26, 'science', 15),
('How many days is a human pregnancy (approximately)?', 280, 'science', 15),
('In what year was the first human genome sequenced?', 2003, 'science', 15),
('How many moons does Saturn have?', 146, 'science', 15),
('What percentage of Earth is covered by water (rounded)?', 71, 'science', 15),
('How many legs does a lobster have?', 10, 'science', 15),
('In what year was DNA structure discovered by Watson and Crick?', 1953, 'science', 15),
('How many brain cells (neurons) does a human have in billions (approximately)?', 86, 'science', 15),
('What is the atomic number of uranium?', 92, 'science', 15),
('How many degrees are in a full circle?', 360, 'science', 15),
('What is the speed of sound in air in m/s (approximately)?', 343, 'science', 15),
('How many toes does a cat have in total?', 18, 'science', 15),
('What is the boiling point of nitrogen in Celsius?', -196, 'science', 15),
('How many meters are in a kilometer?', 1000, 'science', 15),
('How many times does the human heart beat per minute on average?', 72, 'science', 15),
('How many grams is one kilogram?', 1000, 'science', 15),
('In what year was the Hubble Space Telescope launched?', 1990, 'science', 15),
('How many stomachs does a cow have?', 4, 'science', 15),
('What is the atomic number of helium?', 2, 'science', 15),
('How many bones does a shark have?', 0, 'science', 15),
('In what year was the first nuclear power plant opened?', 1954, 'science', 15),
('How many minutes are in a full day?', 1440, 'science', 15),
('What percentage of the human body is water (approximately)?', 60, 'science', 15),
('How many chromosomes does a dog have?', 78, 'science', 15),
('What is the gravitational acceleration on Earth in m/s² (rounded)?', 10, 'science', 15),
('In what year was the first cloned mammal (Dolly the sheep) created?', 1996, 'science', 15),
('How many teeth does a shark have in a lifetime (approximately)?', 30000, 'science', 15),
('What is the atomic number of silver?', 47, 'science', 15),
('How many bones are in the human skull?', 22, 'science', 15),
('In what year was the theory of evolution published by Darwin?', 1859, 'science', 15),
('How many seconds are in a day?', 86400, 'science', 15),

-- MONEY (60 questions)
('In what year was the New York Stock Exchange founded?', 1792, 'money', 15),
('How many cents are in a US dollar?', 100, 'money', 15),
('In what year was the Federal Reserve established?', 1913, 'money', 15),
('What was the approximate peak price of Bitcoin in USD in 2021 (rounded to nearest thousand)?', 69000, 'money', 15),
('In what year did the Great Depression begin?', 1929, 'money', 15),
('How many countries use the Euro as their currency?', 20, 'money', 15),
('In what year was the Euro introduced as physical currency?', 2002, 'money', 15),
('How many US dollar bills are printed each day (approximately in millions)?', 541, 'money', 15),
('In what year did Amazon go public?', 1997, 'money', 15),
('In what year was Apple Inc. founded?', 1976, 'money', 15),
('In what year did the Dot-com bubble burst?', 2000, 'money', 15),
('How many days does it take for a cheque to clear in most countries?', 3, 'money', 15),
('In what year did Google go public?', 2004, 'money', 15),
('How many zeros are in one trillion?', 12, 'money', 15),
('In what year was PayPal founded?', 1998, 'money', 15),
('What is the highest denomination US dollar bill in circulation?', 100, 'money', 15),
('In what year did the 2008 financial crisis peak?', 2008, 'money', 15),
('How many grams of gold are in a troy ounce (rounded)?', 31, 'money', 15),
('In what year was the first credit card (Diners Club) introduced?', 1950, 'money', 15),
('What percentage is the standard VAT rate in the UK?', 20, 'money', 15),
('In what year was VISA founded?', 1958, 'money', 15),
('How many years was Warren Buffett CEO of Berkshire Hathaway by 2024?', 59, 'money', 15),
('In what year did Facebook (Meta) go public?', 2012, 'money', 15),
('What is the standard VAT rate in Germany as a percentage?', 19, 'money', 15),
('In what year was the World Bank founded?', 1944, 'money', 15),
('How many central banks are in the Eurozone (ECB members)?', 20, 'money', 15),
('In what year did Tesla go public?', 2010, 'money', 15),
('What percentage of the world''s gold supply has already been mined (approximately)?', 80, 'money', 15),
('In what year was the IMF (International Monetary Fund) founded?', 1944, 'money', 15),
('How many zeros are in one billion?', 9, 'money', 15),
('In what year was Mastercard founded?', 1966, 'money', 15),
('How many US states have no income tax?', 9, 'money', 15),
('In what year was the first ATM installed (in London)?', 1967, 'money', 15),
('What is the corporate tax rate in Ireland as a percentage?', 12, 'money', 15),
('In what year was the London Stock Exchange founded?', 1801, 'money', 15),
('How many days are in a financial year?', 365, 'money', 15),
('In what year was Coca-Cola first sold?', 1886, 'money', 15),
('How many million dollars is one billion dollars?', 1000, 'money', 15),
('In what year was eBay founded?', 1995, 'money', 15),
('What percentage of global GDP does the US account for (approximately)?', 25, 'money', 15),
('In what year was Goldman Sachs founded?', 1869, 'money', 15),
('How many years does a US patent last?', 20, 'money', 15),
('In what year did Lehman Brothers collapse?', 2008, 'money', 15),
('How many countries are in the G20?', 20, 'money', 15),
('In what year was the Dow Jones Industrial Average created?', 1896, 'money', 15),
('How many weeks are in a financial quarter?', 13, 'money', 15),
('In what year was Alibaba founded?', 1999, 'money', 15),
('What percentage of the world''s transactions are made in cash (approximately)?', 17, 'money', 15),
('In what year was J.P. Morgan founded?', 1799, 'money', 15),
('How many currencies exist in the world (approximately)?', 180, 'money', 15),
('In what year was the first paper money used in China?', 700, 'money', 15),
('How many countries are in OPEC?', 13, 'money', 15),
('What percentage annual return did the S&P 500 average over the last 100 years (approximately)?', 10, 'money', 15),
('In what year was the WTO (World Trade Organization) founded?', 1995, 'money', 15),
('How many euros is one Swiss franc worth, rounded to the nearest whole number?', 1, 'money', 15),
('In what year did China join the WTO?', 2001, 'money', 15),
('How many years did the Great Depression last?', 10, 'money', 15),
('In what year was Bitcoin created?', 2009, 'money', 15),
('What is the top marginal income tax rate in the United States as a percentage?', 37, 'money', 15),
('In what year was the World Economic Forum first held in Davos?', 1971, 'money', 15),

-- GEOGRAPHY (60 questions)
('How many countries are in the world?', 195, 'geography', 15),
('How many countries are in Africa?', 54, 'geography', 15),
('How many countries are in Europe?', 44, 'geography', 15),
('How many countries border France?', 8, 'geography', 15),
('What is the population of China in billions (rounded)?', 1, 'geography', 15),
('How many time zones does Russia span?', 11, 'geography', 15),
('How many countries are in the European Union?', 27, 'geography', 15),
('What is the length of the Great Wall of China in kilometers (rounded to nearest thousand)?', 21000, 'geography', 15),
('How many countries share a border with Germany?', 9, 'geography', 15),
('How many islands does Greece have?', 6000, 'geography', 15),
('What is the area of Russia in million square kilometers (rounded)?', 17, 'geography', 15),
('How many countries are in Asia?', 48, 'geography', 15),
('How many meters above sea level is Mount Everest (rounded to nearest hundred)?', 8800, 'geography', 15),
('How many countries make up the United Kingdom?', 4, 'geography', 15),
('What is the population of the USA in millions (rounded to nearest ten)?', 330, 'geography', 15),
('How many countries border Russia?', 14, 'geography', 15),
('How long is the Amazon River in kilometers (rounded to nearest hundred)?', 6400, 'geography', 15),
('How many countries are in South America?', 12, 'geography', 15),
('What is the area of Vatican City in square meters (approximately)?', 440000, 'geography', 15),
('How many US states are there?', 50, 'geography', 15),
('How many countries are in North America?', 23, 'geography', 15),
('What is the depth of the Mariana Trench in meters (rounded to nearest thousand)?', 11000, 'geography', 15),
('How many countries are in the Middle East?', 18, 'geography', 15),
('How many national parks are in the USA?', 63, 'geography', 15),
('What is the population of India in billions (rounded)?', 1, 'geography', 15),
('How many countries border China?', 14, 'geography', 15),
('What is the length of the Nile River in kilometers (rounded to nearest hundred)?', 6600, 'geography', 15),
('How many cantons does Switzerland have?', 26, 'geography', 15),
('What is the area of Australia in million square kilometers (rounded)?', 8, 'geography', 15),
('How many countries are in Oceania?', 14, 'geography', 15),
('How many countries have a coastline?', 148, 'geography', 15),
('What is the population of Tokyo in millions (rounded)?', 14, 'geography', 15),
('How many rivers flow into the Amazon?', 1100, 'geography', 15),
('How many countries are in the Commonwealth of Nations?', 56, 'geography', 15),
('What is the area of the Sahara Desert in million square kilometers (rounded)?', 9, 'geography', 15),
('How many UNESCO World Heritage Sites are there (approximately)?', 1199, 'geography', 15),
('How many counties are in England?', 48, 'geography', 15),
('What is the population of the world in billions (rounded, as of 2024)?', 8, 'geography', 15),
('How many countries share a border with Brazil?', 10, 'geography', 15),
('What is the height of the Burj Khalifa in meters?', 828, 'geography', 15),
('How many countries are landlocked in Africa?', 16, 'geography', 15),
('How many floors does the Empire State Building have?', 102, 'geography', 15),
('What is the area of the USA in million square kilometers (rounded)?', 10, 'geography', 15),
('How many countries are in the G7?', 7, 'geography', 15),
('What is the length of the Rhine River in kilometers (rounded to nearest hundred)?', 1200, 'geography', 15),
('How many provinces does Canada have?', 10, 'geography', 15),
('What is the area of the Mediterranean Sea in square kilometers (rounded to nearest hundred thousand)?', 2500000, 'geography', 15),
('How many countries share a border with India?', 6, 'geography', 15),
('How many islands does Japan have?', 6852, 'geography', 15),
('What is the population of London in millions (rounded)?', 9, 'geography', 15),
('How many countries are members of the United Nations?', 193, 'geography', 15),
('What is the length of the Danube River in kilometers (rounded to nearest hundred)?', 2900, 'geography', 15),
('How many states does Germany have?', 16, 'geography', 15),
('How many meters tall is the Eiffel Tower?', 330, 'geography', 15),
('How many countries share a border with Mexico?', 3, 'geography', 15),
('How many time zones does the USA span?', 6, 'geography', 15),
('What is the approximate area of Antarctica in million square kilometers?', 14, 'geography', 15),
('How many districts does London have?', 33, 'geography', 15),
('What is the population of Brazil in millions (rounded to nearest ten)?', 210, 'geography', 15),
('How many countries have French as an official language?', 29, 'geography', 15),

-- SPORTS (60 questions)
('How many gold medals did Michael Phelps win across all Olympics?', 23, 'sports', 15),
('How many World Cup titles has Brazil won?', 5, 'sports', 15),
('How many Grand Slam titles did Roger Federer win?', 20, 'sports', 15),
('How many rings does an NBA championship trophy have?', 5, 'sports', 15),
('In what year was the first FIFA World Cup held?', 1930, 'sports', 15),
('How many players are on a football (soccer) team on the pitch?', 11, 'sports', 15),
('How many points is a touchdown worth in American Football?', 6, 'sports', 15),
('In what year did Usain Bolt set the 100m world record?', 2009, 'sports', 15),
('How many Grand Slam titles has Novak Djokovic won (as of 2024)?', 24, 'sports', 15),
('How many meters long is an Olympic swimming pool?', 50, 'sports', 15),
('How many players are on a basketball team on the court?', 5, 'sports', 15),
('In what year did Muhammad Ali win his first world heavyweight title?', 1964, 'sports', 15),
('How many holes are in a standard golf course?', 18, 'sports', 15),
('How many points must a team win by in a tennis tiebreak?', 7, 'sports', 15),
('In what year were the first modern Olympic Games held?', 1896, 'sports', 15),
('How many Formula 1 World Championships did Michael Schumacher win?', 7, 'sports', 15),
('How many players are in a rugby union team?', 15, 'sports', 15),
('What is the marathon distance in kilometers (rounded)?', 42, 'sports', 15),
('In what year did Lionel Messi win his first Ballon d''Or?', 2009, 'sports', 15),
('How many sets are in a men''s Grand Slam tennis final?', 5, 'sports', 15),
('How many seconds does Usain Bolt''s 100m world record stand at (rounded)?', 9, 'sports', 15),
('In what year was the Premier League founded?', 1992, 'sports', 15),
('How many players are on a volleyball team on the court?', 6, 'sports', 15),
('How many Formula 1 World Championships did Lewis Hamilton win?', 7, 'sports', 15),
('How many yards is an American football field?', 100, 'sports', 15),
('In what year did Tiger Woods win his first Masters?', 1997, 'sports', 15),
('How many countries participated in the 2022 FIFA World Cup?', 32, 'sports', 15),
('How many points is a try worth in rugby union?', 5, 'sports', 15),
('In what year was the NBA founded?', 1946, 'sports', 15),
('How many grams does a tennis ball weigh (approximately)?', 57, 'sports', 15),
('How many times did Real Madrid win the UEFA Champions League (as of 2024)?', 15, 'sports', 15),
('In what year did Cristiano Ronaldo win his first Ballon d''Or?', 2008, 'sports', 15),
('How many points are needed to win a set in tennis (standard)?', 6, 'sports', 15),
('How many Olympic gold medals did Usain Bolt win in total?', 8, 'sports', 15),
('In what year was the Super Bowl first played?', 1967, 'sports', 15),
('How many players are on a baseball team on the field?', 9, 'sports', 15),
('How many laps is the Le Mans 24-hour race (approximately)?', 380, 'sports', 15),
('In what year did the Chicago Bulls win their first NBA championship?', 1991, 'sports', 15),
('How many points is a slam dunk worth in basketball?', 2, 'sports', 15),
('How many Grand Slam titles did Serena Williams win?', 23, 'sports', 15),
('In what year was the Rugby World Cup first held?', 1987, 'sports', 15),
('How many meters high is the net in tennis (at the center)?', 1, 'sports', 15),
('How many wins did Ayrton Senna have in Formula 1?', 41, 'sports', 15),
('In what year was the Champions League rebranded from the European Cup?', 1992, 'sports', 15),
('How many times did Manchester United win the UEFA Champions League?', 3, 'sports', 15),
('How many events are in the Olympic decathlon?', 10, 'sports', 15),
('In what year did the Chicago Cubs last win the World Series before 2016?', 1908, 'sports', 15),
('How many rounds are in a professional boxing world title fight?', 12, 'sports', 15),
('How many times did Pete Sampras win Wimbledon?', 7, 'sports', 15),
('In what year were the Beijing Olympic Games held?', 2008, 'sports', 15),
('How many points is a three-pointer worth in basketball?', 3, 'sports', 15),
('How many Grand Slam titles did Rafael Nadal win?', 22, 'sports', 15),
('In what year was the first Tour de France held?', 1903, 'sports', 15),
('How many red cards were shown at the 2006 FIFA World Cup?', 28, 'sports', 15),
('How many players are on an ice hockey team on the ice?', 6, 'sports', 15),
('In what year did Argentina last win the FIFA World Cup before 2022?', 1986, 'sports', 15),
('How many countries competed in the first modern Olympics in 1896?', 14, 'sports', 15),
('How many minutes is a standard football (soccer) match?', 90, 'sports', 15),
('In what year was Pelé born?', 1940, 'sports', 15),
('How many majors did Jack Nicklaus win in golf?', 18, 'sports', 15)
;
